[package]
name = "engine-z"
version = "0.1.0"
authors = ["Carsten Kragelund <carsten@kragelund.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
